In [2]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.add(2,5)

7

In [4]:
np.subtract(4,7) 

-3

In [5]:
np.multiply(4,2)

8

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((4,2),54)

array([[54, 54],
       [54, 54],
       [54, 54],
       [54, 54]])

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [11]:
np.random.random((3,6))

array([[7.46933267e-01, 2.25826148e-01, 1.37616622e-02, 7.23177816e-02,
        6.60157580e-01, 5.95562477e-01],
       [8.01062490e-01, 2.58997745e-01, 8.29994139e-01, 8.62111124e-01,
        5.84115979e-01, 1.46247020e-05],
       [8.71510572e-01, 4.23148831e-02, 7.99090192e-01, 4.47436772e-01,
        3.13385810e-01, 8.81027418e-01]])

In [12]:
a=np.eye(4)

In [13]:
np.empty(3)

array([0. , 2.5, 5. ])

In [26]:
c=np.random.randint(0,10,(3,3))
c

array([[9, 0, 3],
       [6, 2, 6],
       [1, 5, 2]])

In [16]:
np.shape(a)

(4, 4)

In [17]:
np.size(a)

16

In [19]:
a.dtype

dtype('float64')

In [20]:
a.data

In [21]:
a.itemsize

8

In [22]:
a.ndim

2

In [37]:
b=np.random.default_rng(1)
b

Generator(PCG64) at 0x2A2D8F7EB88

In [32]:
c=np.random.randint(0,10,(3,3))
c

array([[1, 4, 3],
       [6, 9, 6],
       [2, 6, 2]])

In [33]:
c.min()

1

In [34]:
c.max()

9

In [35]:
c.mean()

4.333333333333333

In [36]:
c.sum()

39

In [38]:
np.exp(c)

array([[2.71828183e+00, 5.45981500e+01, 2.00855369e+01],
       [4.03428793e+02, 8.10308393e+03, 4.03428793e+02],
       [7.38905610e+00, 4.03428793e+02, 7.38905610e+00]])

In [47]:
np.random.seed(0)
np.random.random((3,5))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [49]:
c.ravel()

array([1, 4, 3, 6, 9, 6, 2, 6, 2])

In [50]:
np.abs(c)

array([[1, 4, 3],
       [6, 9, 6],
       [2, 6, 2]])

In [51]:
np.pi

3.141592653589793

In [52]:
np.sin(c)

array([[ 0.84147098, -0.7568025 ,  0.14112001],
       [-0.2794155 ,  0.41211849, -0.2794155 ],
       [ 0.90929743, -0.2794155 ,  0.90929743]])

In [53]:
np.cos(c)

array([[ 0.54030231, -0.65364362, -0.9899925 ],
       [ 0.96017029, -0.91113026,  0.96017029],
       [-0.41614684,  0.96017029, -0.41614684]])

In [54]:
np.tan(c)

array([[ 1.55740772,  1.15782128, -0.14254654],
       [-0.29100619, -0.45231566, -0.29100619],
       [-2.18503986, -0.29100619, -2.18503986]])

In [58]:
np.arcsin(0.5)

0.5235987755982989

In [59]:
np.arccos(0.5)

1.0471975511965979

In [60]:
np.arctan(0.5)

0.4636476090008061

In [61]:
np.log(c)

array([[0.        , 1.38629436, 1.09861229],
       [1.79175947, 2.19722458, 1.79175947],
       [0.69314718, 1.79175947, 0.69314718]])

In [62]:
np.log2(c)

array([[0.       , 2.       , 1.5849625],
       [2.5849625, 3.169925 , 2.5849625],
       [1.       , 2.5849625, 1.       ]])

In [63]:
np.log10(c)

array([[0.        , 0.60205999, 0.47712125],
       [0.77815125, 0.95424251, 0.77815125],
       [0.30103   , 0.77815125, 0.30103   ]])

In [64]:
np.add.reduce(c)

array([ 9, 19, 11])

In [65]:
np.multiply.reduce(c)

array([ 12, 216,  36])

In [66]:
np.add.accumulate(c)

array([[ 1,  4,  3],
       [ 7, 13,  9],
       [ 9, 19, 11]], dtype=int32)

In [67]:
np.multiply.accumulate(c)

array([[  1,   4,   3],
       [  6,  36,  18],
       [ 12, 216,  36]], dtype=int32)

In [68]:
np.power(3,5)

243

In [72]:
np.hsplit(c,3)

[array([[1],
        [6],
        [2]]),
 array([[4],
        [9],
        [6]]),
 array([[3],
        [6],
        [2]])]

In [73]:
np.vsplit(c,3)

[array([[1, 4, 3]]), array([[6, 9, 6]]), array([[2, 6, 2]])]

In [74]:
np.absolute(c)

array([[1, 4, 3],
       [6, 9, 6],
       [2, 6, 2]])

In [75]:
np.prod(c)

93312

In [76]:
np.std(c)

2.449489742783178

In [77]:
np.var(c)

6.0